**DATA CLEANING FOR MACHINE LEARNING USING PYTHON**

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("House_Price_Data_123_Rows.csv")

In [3]:
df

    House_ID  Size_sqft  Bedrooms   Location  Age_Years Garage   Price_USD
0       H001       3350         4     Monaco         19    YES  $1,638,000
1       H002       1950         3      Dubai         -3    Yes    $734,200
2       H003       2250         3      Paris         21    Yes    $794,200
3       H004          0         5  Singapore         27    YES  $1,210,500
4       H005      -1200         5      Paris         15    YES  $1,356,700
..       ...        ...       ...        ...        ...    ...         ...
118     H119       2850         4      Dubai         26     No    $835,800
119     H120       3000         4      Tokyo         27    Yes  $1,066,400
120     H121       3550         5     Monaco          1    Yes  $1,808,500
121     H122       3100         5      Paris         24     No  $1,253,200
122     H123        850         2  Singapore         15    YES    $334,700

[123 rows x 7 columns]

**COPY THE DATASET**

In [5]:
#why i copied this dataset is because i dont want to change the actual dataset
data = df.copy()
data

    House_ID  Size_sqft  Bedrooms   Location  Age_Years Garage   Price_USD
0       H001       3350         4     Monaco         19    YES  $1,638,000
1       H002       1950         3      Dubai         -3    Yes    $734,200
2       H003       2250         3      Paris         21    Yes    $794,200
3       H004          0         5  Singapore         27    YES  $1,210,500
4       H005      -1200         5      Paris         15    YES  $1,356,700
..       ...        ...       ...        ...        ...    ...         ...
118     H119       2850         4      Dubai         26     No    $835,800
119     H120       3000         4      Tokyo         27    Yes  $1,066,400
120     H121       3550         5     Monaco          1    Yes  $1,808,500
121     H122       3100         5      Paris         24     No  $1,253,200
122     H123        850         2  Singapore         15    YES    $334,700

[123 rows x 7 columns]

**REMOVE THE DUPLICATE ROWS IN DATASET**

In [7]:
 # this will tell us is there any duplicated row by true or false
data.duplicated()

# this will give the total number of duplicated rows , but in my dataset i dont have any duplicated row
data.duplicated().sum() 


#now agr koi duplicate row hoti usko remove aise karty 

data = data.drop_duplicates() # ye duplicate rows ko delete krta hai ayi samaj

np.int64(0)

**REMOVING IRRELEVENT COLUMNS**

In [22]:
#for example dataset mai aise columns hoty hai jinko hamari research ke sath zyada kuch nahi hota , 
#agr koi kaam nahi hai fir udaa dena hai na columns unko
#jaise house id ko house price prediction ke sath kya karna hai kuch nahi, toh udaa do isko

data.shape # total number of rows and columns dega 

data.columns # gives every column name

Index(['House_ID', 'Size_sqft', 'Bedrooms', 'Location', 'Age_Years', 'Garage',
       'Price_USD'],
      dtype='str')

In [ ]:

#remove house Id column

data = data.drop("House_ID",axis="columns")

In [30]:
data.shape
#now i can clearly see that the house id column is removed....😂😂😂

(123, 6)

**CHECKING MISSING VALUES**

In [32]:
data.count() # gives number of entries in each column

Size_sqft    123
Bedrooms     123
Location     123
Age_Years    123
Garage       123
Price_USD    123
dtype: int64

In [34]:
data.isnull().sum() # gives values if there is any null value present 

#Inorder to replace any value 
#data.replave("can be any value",np.nan)

Size_sqft    0
Bedrooms     0
Location     0
Age_Years    0
Garage       0
Price_USD    0
dtype: int64

**FIXING INCONSISTENT FORMATS**

In [35]:
#Like small capital letters 
#in garage column there is not any standard formatting , like YES ,Yes ,No ,NO etc
#to fix
data["Garage"] = data["Garage"].str.title()

In [36]:
data

     Size_sqft  Bedrooms   Location  Age_Years Garage   Price_USD
0         3350         4     Monaco         19    Yes  $1,638,000
1         1950         3      Dubai         -3    Yes    $734,200
2         2250         3      Paris         21    Yes    $794,200
3            0         5  Singapore         27    Yes  $1,210,500
4        -1200         5      Paris         15    Yes  $1,356,700
..         ...       ...        ...        ...    ...         ...
118       2850         4      Dubai         26     No    $835,800
119       3000         4      Tokyo         27    Yes  $1,066,400
120       3550         5     Monaco          1    Yes  $1,808,500
121       3100         5      Paris         24     No  $1,253,200
122        850         2  Singapore         15    Yes    $334,700

[123 rows x 6 columns]

**CHECKING IMPOSSIBLE VALUES**

In [39]:
#NEGATIVE VALUES IN SIZE_SQFT

data.loc[data["Size_sqft"]<=0,"Size_sqft"] = np.nan
#agr sizesqft column mai koi value 0 ya ussy chota huva usko null krdo
data.loc[data["Age_Years"] < 0 , "Age_Years"] = np.nan

data.head()

   Size_sqft  Bedrooms   Location  Age_Years Garage   Price_USD
0     3350.0         4     Monaco       19.0    Yes  $1,638,000
1     1950.0         3      Dubai        NaN    Yes    $734,200
2     2250.0         3      Paris       21.0    Yes    $794,200
3        NaN         5  Singapore       27.0    Yes  $1,210,500
4        NaN         5      Paris       15.0    Yes  $1,356,700

**CHECKING INVALID LABELS**

In [40]:
#This means if the target variable contains null data or invalid data we will drop this thats it
data = data.dropna(subset=["Price_USD"])

In [41]:
data.to_csv("Updated_House_Dataset.csv",index=False)